name: Proto

on:
  push:
    branches:
      - proto/*
jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12.x
          - 14.x
        suite:
          - cli
          - plugin

        include:
          - os: macos-latest
            env: env
            versions: ""
          - os: ubuntu-latest
            env: env
            versions: ""
          # Running natively under Windows requires some further work on paths
          # and file access patterns.
          - os: windows-latest
            env: Get-ChildItem Env:\
            versions: choco --version

    timeout-minutes: 40

    runs-on: ${{ matrix.os }}

    steps:
      - name: Gather environment data
        run: |
          ${{ matrix.env }}
          node --version
          npm --version
          yarn --version

      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      # Publish tests won't work if we haven't configured our committer details.
      - name: Configure Git user
        run: |
          git config --global user.name CI
          git config --global user.email ci@dendron.so

      - name: Restore typescript lib cache
        uses: actions/cache@v2
        id: ts-cache
        with:
          path: |
            packages/*/lib/*
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Bootstrap
        run: yarn bootstrap:bootstrap
        shell: bash

      - name: Build
        run: yarn bootstrap:buildCI
        shell: bash

      - name: Start Xvfb
        if: runner.os == 'Linux' && matrix.suite == 'plugin'
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo 'DISPLAY=:99.0' >>$GITHUB_ENV

      - name: Run tests
        run: yarn ci:test:${{ matrix.suite }}
        timeout-minutes: 30
