# Builds and publishes the release. This will publish packages to npm and
# publish the release extension to the VS Code and Open VSX Marketplaces. This
# is manually triggered once the release build is smoke-tested and ready for
# release.
name: Proto

on:
  push:
    branches:
      - proto/*
jobs:
  test:
    strategy:
      # Allow other matrix jobs to continue after one fails, allowing us to
      # isolate platform-specific issues.
      fail-fast: false

      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        node-version:
          - 12.x
          # - 14.x
        suite:
          - cli
          # - plugin

        include:
          # - os: macos-latest
          #   env: env
          #   versions: ""
          - os: ubuntu-latest
            env: env
            versions: ""
          # Running natively under Windows requires some further work on paths
          # and file access patterns.
          # - os: windows-latest
          #   env: Get-ChildItem Env:\
          #   versions: choco --version

    timeout-minutes: 40

    runs-on: ${{ matrix.os }}

    steps:
      - name: Gather environment data
        run: |
          ${{ matrix.env }}
          node --version
          npm --version
          yarn --version

      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      # Publish tests won't work if we haven't configured our committer details.
      - name: Configure Git user
        run: |
          git config --global user.name CI
          git config --global user.email ci@dendron.so

      - name: Restore typescript lib cache
        uses: actions/cache@v2
        id: ts-cache
        with:
          path: |
            packages/*/lib/*
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Bootstrap
        run: yarn bootstrap:bootstrap
        shell: bash

      - name: Build
        run: yarn bootstrap:buildCI
        shell: bash

      # - name: Run tests
      #   run: yarn ci:test:${{ matrix.suite }}
      #   timeout-minutes: 30
